In [31]:
# Import the data
import pandas as pd
train = pd.read_csv("child-mind-institute-problematic-internet-use/train.csv")
test = pd.read_csv("child-mind-institute-problematic-internet-use/test.csv")

In [32]:
SEASON_COLS = [
    "Basic_Demos-Enroll_Season", 
    "CGAS-Season", 
    "Physical-Season", 
    "Fitness_Endurance-Season", 
    "FGC-Season", 
    "BIA-Season", 
    "PAQ_A-Season", 
    "PAQ_C-Season", 
    "SDS-Season",
    "PreInt_EduHx-Season"]

In [33]:
TARGET_COLS = [
    "PCIAT-Season",
    "PCIAT-PCIAT_01",
    "PCIAT-PCIAT_02",
    "PCIAT-PCIAT_03",
    "PCIAT-PCIAT_04",
    "PCIAT-PCIAT_05",
    "PCIAT-PCIAT_06",
    "PCIAT-PCIAT_07",
    "PCIAT-PCIAT_08",
    "PCIAT-PCIAT_09",
    "PCIAT-PCIAT_10",
    "PCIAT-PCIAT_11",
    "PCIAT-PCIAT_12",
    "PCIAT-PCIAT_13",
    "PCIAT-PCIAT_14",
    "PCIAT-PCIAT_15",
    "PCIAT-PCIAT_16",    
    "PCIAT-PCIAT_17",
    "PCIAT-PCIAT_18",
    "PCIAT-PCIAT_19",
    "PCIAT-PCIAT_20",
    "PCIAT-PCIAT_Total"
]

In [34]:
train_df = train.drop(TARGET_COLS,axis=1)

In [35]:
train_df

,id,Basic_Demos-Enroll_Season,Basic_Demos-Age,Basic_Demos-Sex,CGAS-Season,CGAS-CGAS_Score,Physical-Season,Physical-BMI,Physical-Height,Physical-Weight,...,PAQ_A-Season,PAQ_A-PAQ_A_Total,PAQ_C-Season,PAQ_C-PAQ_C_Total,SDS-Season,SDS-SDS_Total_Raw,SDS-SDS_Total_T,PreInt_EduHx-Season,PreInt_EduHx-computerinternet_hoursday,sii
0,00008ff9,Fall,5,0,Winter,51.0,Fall,16.877316,46.0,50.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fall,3.0,2.0
1,000fd460,Summer,9,0,NaN,NaN,Fall,14.035590,48.0,46.0,...,NaN,NaN,Fall,2.340,Fall,46.0,64.0,Summer,0.0,0.0
2,00105258,Summer,10,1,Fall,71.0,Fall,16.648696,56.5,75.6,...,NaN,NaN,Summer,2.170,Fall,38.0,54.0,Summer,2.0,0.0
3,00115b9f,Winter,9,0,Fall,71.0,Summer,18.292347,56.0,81.6,...,NaN,NaN,Winter,2.451,Summer,31.0,45.0,Winter,0.0,1.0
4,0016bb22,Spring,18,1,Summer,NaN,NaN,NaN,NaN,NaN,...,Summer,1.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3955,ff8a2de4,Fall,13,0,Spring,60.0,Fall,16.362460,59.5,82.4,...,NaN,NaN,Winter,3.260,Winter,35.0,50.0,Fall,1.0,1.0
3956,ffa9794a,Winter,10,0,NaN,NaN,Spring,18.764678,53.5,76.4,...,NaN,NaN,Winter,2.340,NaN,NaN,NaN,Winter,0.0,NaN
3957,ffcd4dbd,Fall,11,0,Spring,68.0,Winter,21.441500,60.0,109.8,...,NaN,NaN,Winter,2.729,Winter,56.0,77.0,Fall,0.0,1.0
3958,ffed1dd5,Spring,13,0,Spring,70.0,Winter,12.235895,70.7,87.0,...,NaN,NaN,Spring,3.300,Spring,33.0,47.0,Spring,1.0,0.0
3959,ffef538e,Spring,11,0,NaN,NaN,Winter,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Spring,1.0,NaN

In [36]:
season_mapping = {'Spring': 0, 'Summer': 1, 'Fall': 2, 'Winter': 3}

In [37]:
for col in SEASON_COLS:
    train_df[col] = train_df[col].map(season_mapping)

In [38]:
#train_df = train_df.dropna(subset=['sii'])

In [39]:
train_df

,id,Basic_Demos-Enroll_Season,Basic_Demos-Age,Basic_Demos-Sex,CGAS-Season,CGAS-CGAS_Score,Physical-Season,Physical-BMI,Physical-Height,Physical-Weight,...,PAQ_A-Season,PAQ_A-PAQ_A_Total,PAQ_C-Season,PAQ_C-PAQ_C_Total,SDS-Season,SDS-SDS_Total_Raw,SDS-SDS_Total_T,PreInt_EduHx-Season,PreInt_EduHx-computerinternet_hoursday,sii
0,00008ff9,2,5,0,3.0,51.0,2.0,16.877316,46.0,50.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,3.0,2.0
1,000fd460,1,9,0,NaN,NaN,2.0,14.035590,48.0,46.0,...,NaN,NaN,2.0,2.340,2.0,46.0,64.0,1.0,0.0,0.0
2,00105258,1,10,1,2.0,71.0,2.0,16.648696,56.5,75.6,...,NaN,NaN,1.0,2.170,2.0,38.0,54.0,1.0,2.0,0.0
3,00115b9f,3,9,0,2.0,71.0,1.0,18.292347,56.0,81.6,...,NaN,NaN,3.0,2.451,1.0,31.0,45.0,3.0,0.0,1.0
4,0016bb22,0,18,1,1.0,NaN,NaN,NaN,NaN,NaN,...,1.0,1.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3955,ff8a2de4,2,13,0,0.0,60.0,2.0,16.362460,59.5,82.4,...,NaN,NaN,3.0,3.260,3.0,35.0,50.0,2.0,1.0,1.0
3956,ffa9794a,3,10,0,NaN,NaN,0.0,18.764678,53.5,76.4,...,NaN,NaN,3.0,2.340,NaN,NaN,NaN,3.0,0.0,NaN
3957,ffcd4dbd,2,11,0,0.0,68.0,3.0,21.441500,60.0,109.8,...,NaN,NaN,3.0,2.729,3.0,56.0,77.0,2.0,0.0,1.0
3958,ffed1dd5,0,13,0,0.0,70.0,3.0,12.235895,70.7,87.0,...,NaN,NaN,0.0,3.300,0.0,33.0,47.0,0.0,1.0,0.0
3959,ffef538e,0,11,0,NaN,NaN,3.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN

In [40]:
id_df = train_df['id']
train_df.drop(columns=['id'], inplace=True)

In [41]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='median')
train_df_imputed = pd.DataFrame(imputer.fit_transform(train_df), columns=train_df.columns)
#X_test = pd.DataFrame(imputer.fit_transform(X_test), columns=X_test.columns)

In [42]:
train_df_imputed['sii'] = train_df_imputed['sii'].round().astype(int)

In [43]:
from sklearn.model_selection import train_test_split
X_train = train_df_imputed.drop(columns=['sii'])  # 假設 'category' 是標籤欄位
y_train = train_df_imputed['sii']
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.3, random_state=42)

In [44]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# 1. 初始化模型
model = RandomForestClassifier(random_state=42)

# 2. 訓練模型
model.fit(X_train, y_train)

# 3. 在驗證集上進行預測
y_val_pred = model.predict(X_val)

# 4. 計算準確率
accuracy = accuracy_score(y_val, y_val_pred)
print(f"Validation Accuracy: {accuracy:.4f}")

# 5. 顯示混淆矩陣和分類報告
print("Confusion Matrix:")
print(confusion_matrix(y_val, y_val_pred))

print("\nClassification Report:")
print(classification_report(y_val, y_val_pred))

Validation Accuracy: 0.7121
Confusion Matrix:
[[806  26   8   0]
 [180  27   8   1]
 [ 82  25  13   0]
 [  6   4   2   0]]

Classification Report:
              precision    recall  f1-score   support

           0       0.75      0.96      0.84       840
           1       0.33      0.12      0.18       216
           2       0.42      0.11      0.17       120
           3       0.00      0.00      0.00        12

    accuracy                           0.71      1188
   macro avg       0.37      0.30      0.30      1188
weighted avg       0.63      0.71      0.65      1188